---
- name: "[APACHE] -  Required and recommended packages are installed."
  package: "name={{ item }} state=present"
  with_flattened:
    - "{{ nextcloud_web.apache2.pkg_inst }}"
    - "{{ nextcloud_web.pkg_dep }}"
    - "{{ nextcloud_db[nextcloud_db_backend].php}}"
  notify: start apache

- block:
  - name: "[APACHE] -  Configure backports."
    apt_repository:
      repo: "deb {{nextcloud_backports.repo}} {{nextcloud_backports.name}} {{nextcloud_backports.env}}"
      state: present
      update_cache: yes
    ignore_errors: yes # fix for travis ci
  - name: "[APACHE] -  Install from backports."
    apt: "name={{ item }} state=latest default_release={{nextcloud_backports.name}}"
    with_flattened:
      - "{{nextcloud_backports.pkg}}"
  when: ansible_os_family == "Debian" and nextcloud_backports is defined

- name: "[APACHE] -  enable APC for php CLI"
  lineinfile:
    dest: "{{ nextcloud_php_dir }}/cli/php.ini"
    line: "apc.enable_cli = 1"
    insertbefore: "^; End:$"
    state: present
    # validate: "/usr/sbin/{{ php_bin }} -t #%s"

- name: "[APACHE] -  Required Apache2 modules are enabled"
  apache2_module: state=present name={{ item }}
  with_items:
    - ssl
    - rewrite
    - headers
    - env
    - dir
    - mime
  notify: restart apache

- name: "[APACHE] -  generate Nextcloud configuration for apache"
  template:
    dest: /etc/apache2/sites-available/nc_{{ nextcloud_instance_name }}.conf
    src: "{{nextcloud_websrv_template}}"
  notify: reload apache

- name: "[APACHE] -  Enable Nextcloud site in apache conf"
  file:
    path: /etc/apache2/sites-enabled/nc_{{ nextcloud_instance_name }}.conf
    src: /etc/apache2/sites-available/nc_{{ nextcloud_instance_name }}.conf
    state: link
  notify: reload apache
