---
- block:
  - set_fact: nextcloud_cert_file="/etc/ssl/{{ nextcloud_trusted_domain }}.crt"
  - set_fact: nextcloud_cert_key_file="/etc/ssl/{{ nextcloud_trusted_domain }}.key"
  - name: "[TLS] - create self-signed SSL cert"
    command: >
      openssl req -new -nodes -x509 
      -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=${hostname --fqdn}"
      -days 365
      -keyout {{ nextcloud_cert_key_file }}
      -out {{nextcloud_cert_file }}
      -extensions v3_ca
    args:
      creates: "{{ nextcloud_cert_key_file }}"
  - name: "[TLS] - change permissions"
    file:
      path: "{{ item }}"
      mode: 0640
      group: "{{ websrv_group }}"
    with_items:
      - "{{ nextcloud_cert_key_file }}"
      - "{{nextcloud_cert_file }}"
  when: nextcloud_cert_method == "self-signed"