---
#########
# Run command line installation.
# the web server must be running by now in order to launch the installation
- name: Trigger all pending handlers
  meta: flush_handlers

- name: "[NC] - Setting directory ownership & permissions for the data folder"
  file:
    path: "{{ nextcloud_data_dir }}"
    mode: u=rwX,g=rX,o-rwx
    recurse: yes
    state: directory
    owner: "{{ websrv_user }}"
    group: "{{ websrv_group }}"

- name: "[NC] - generate {{ nextcloud_admin_name }} password:"
  set_fact: nextcloud_admin_pwd="{{ lookup( 'password', 'nextcloud_instances/'+ nextcloud_trusted_domain +'/web_admin.pwd length=10' ) }}"
  when: nextcloud_admin_pwd is not defined

- name: "[NC] - Set temporary permissions for command line installation."
  file:
    path: "{{ nextcloud_webroot }}"
    state: directory
    recurse: yes
    owner: "{{ websrv_user }}"
    group: "{{ websrv_group }}"

# fix for mariadb with occ    
- set_fact: nextcloud_tmp_backend="{{ nextcloud_db_backend }}"
  when: nextcloud_db_backend != "mariadb"
- set_fact: nextcloud_tmp_backend="mysql"
  when: nextcloud_db_backend == "mariadb"

- block:
  - name: "[NC] - Run occ installation command"
    # become: true
    become_user: "{{ websrv_user }}"
    command: >
        php occ  maintenance:install
        --database {{ nextcloud_tmp_backend }}
        --database-host {{ nextcloud_db_host }}
        --database-name {{ nextcloud_db_name }}
        --database-user {{ nextcloud_db_admin }}
        --database-pass {{ nextcloud_db_pwd }}
        --admin-user {{ nextcloud_admin_name }}
        --admin-pass {{ nextcloud_admin_pwd }}
        --data-dir {{ nextcloud_data_dir }}
    args:
      chdir: "{{ nextcloud_webroot }}"
      creates: "{{ nextcloud_webroot }}/config/config.php"
    notify: "reload {{ nextcloud_websrv }}"

  - name: "[NC] - Verify config.php"
    stat: path="{{ nextcloud_webroot }}/config/config.php"
    register: conf

  - name: "[NC] - Verify config.php - check filesize"
    file:
      path: "{{ nextcloud_webroot }}/config/config.php"
      state: absent
      # will always set the state to failed.
      failed_when: True
    when: conf.stat.size is undefined or conf.stat.size <= 100

  - name: "[NC] - Verify config.php - php syntax check"
    command: "php -l {{ nextcloud_webroot }}/config/config.php"

  rescue:
    - name: "[NC] - removing config.php when occ fail"
      file:
        path: "{{ nextcloud_webroot }}/config/config.php"
        state: absent
      # will always set the state to failed.
      failed_when: True

- name: "[NC] - Add {{ nextcloud_trusted_domain }} in config.php"
  lineinfile:
    dest: "{{ nextcloud_webroot }}/config/config.php"
    line: "    1 => '{{ nextcloud_trusted_domain }}',"
    insertafter: "0 => '"
    state: present

- name: "[NC] - Add local cache and urandom in config.php"
  lineinfile:
    dest: "{{ nextcloud_webroot }}/config/config.php"
    line: "{{ item }}"
    insertbefore: "\\);"
    state: present
  with_items:
    - "  'memcache.local' => '\\OC\\Memcache\\APCu',"
    - "  'open_basedir' => '/dev/urandom'"

- name: "[NC] - Ensure Nextcloud directories are 0750"
  command: find {{ nextcloud_data_dir }} -type d -exec chmod -c 0750 {} \;
  register: chmod_result
  changed_when: "chmod_result.stdout != \"\""

- name: "[NC] - Ensure Nextcloud files are 0640"
  command: find {{ nextcloud_data_dir }} -type f -exec chmod -c 0640 {} \;
  register: chmod_result
  changed_when: "chmod_result.stdout != \"\""

- name: "[NC] - Setting stronger directory ownership"
  file:
    path: "{{ nextcloud_webroot }}/{{ item }}/"
    recurse: yes
    owner: "{{ websrv_user }}"
    group: "{{ websrv_group }}"
    state: directory
  with_items:
    - apps
    - assets
    - config
    - themes
    - updater

- name: "[NC] - Give execution permission to occ"
  file:
    path: "{{ nextcloud_webroot }}/occ"
    mode: 0750

