---
- name: "[REDIS] -  Required packages are installed."
  package: "name={{ item }} state=present"
  with_items:
    - redis-server
    - "{{ php_pkg_spe }}"
  notify: start redis

- name: "[REDIS] -  Redis configuration is present."
  template:
    dest: /etc/redis/redis.conf
    src: templates/redis.conf.j2
  notify: restart redis

