---
# additionnal setup for OS depedent environment


- name: "[ENV] - ca-certificate are up to date"
  # needed for downloading from download.nextcloud.com : letsencrypt may not be trusted on older OS
  apt: update_cache=yes name=ca-certificates state=latest
  when: ansible_os_family in [ "Debian" ]
  
- name: "[ENV] - Load environment for OS using php 5 "
  include_vars: defaults/php5_env.yml
  when: ansible_distribution_release in [ "trusty", "jessie" ]
  
- name: "[ENV] - Load environment for OS using php 7.0 "
  include_vars: defaults/php7.0_env.yml
  when: ansible_distribution_release in [ "xenial" ]