---
# additionnal setup and fixes for OS dependent environment
- name: "controls nextcloud_trusted_domain type"
  fail:
    msg: "New versions require nextcloud_trusted_domain to be declared as a list."
  when: nextcloud_trusted_domain is string

# - set_fact:
#     websrv_user: "{{supported_os[ansible_distribution][ansible_distribution_release][nextcloud_websrv].user}}"
# - set_fact:
#     websrv_group: "{{supported_os[ansible_distribution][ansible_distribution_release][nextcloud_websrv].group}}"
- name: "[ENV] - Load OS parameters "
  include_vars: "{{ role_path }}/vars/{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"

- name: "[ENV] - requirements are installed"
  package:
    name: "{{ item }}"
    state: latest
  with_flattened:
    - "{{ nextcloud_spec.required }}"
    - "{{ nextcloud_spec[nextcloud_archive_format] }}"

  # fix for OS not using sudo :
  # defining if sudo is installed or not
- block:
    - name: "[ENV] - checking sudo is installed."
      shell: "dpkg -l sudo"
      changed_when: False
      when: ansible_os_family == 'Debian'
  rescue:
    - name: "[ENV] - rolling back to su."
      set_fact: ansible_become_method="su"
